version: '3.8'
services:
  openldap:
    build:
      context: ./ldap
      dockerfile: Dockerfile
    container_name: my-local-ldap
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d
      
      
    environment:
      LDAP_ORGANISATION: "My Local Dev"
      LDAP_DOMAIN: "dev.local"
      LDAP_ADMIN_PASSWORD: "adminpassword"
    networks:
      - ldap-net

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: my-local-ldap-admin
    ports:
      - "8080:80"
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - openldap
    networks:
      - ldap-net

networks:
  ldap-net:

volumes:
  ldap_data:
  ldap_config: