-- 建立 layout_tasks 資料表
CREATE TABLE layout_tasks (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id VARCHAR2(50) NOT NULL,
    ip_name VARCHAR2(100) NOT NULL,
    designer VARCHAR2(100),
    layout_owner VARCHAR2(100),
    schematic_freeze DATE,
    lvs_clean DATE,
    layout_leader_schematic_freeze DATE,
    layout_leader_lvs_clean DATE,
    planned_mandays NUMBER,
    actual_hours CLOB DEFAULT '[]',
    weekly_weights CLOB DEFAULT '[]',
    version NUMBER DEFAULT 1,
    rework_note VARCHAR2(4000),
    layout_closed NUMBER(1) DEFAULT 0,
    modified_by VARCHAR2(100),
    last_modified TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT unique_project_ip UNIQUE (project_id, ip_name)
);

-- 建立索引
CREATE INDEX idx_layout_tasks_project_id ON layout_tasks(project_id);
CREATE INDEX idx_layout_tasks_ip_name ON layout_tasks(ip_name); 