-- 建立 weekly_weights 資料表
CREATE TABLE layout_weekly_weights (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    layout_id NUMBER NOT NULL,
    week VARCHAR2(10) NOT NULL,
    weight NUMBER(5,2) NOT NULL,
    updated_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_by VARCHAR2(100),
    role VARCHAR2(50),
    version NUMBER DEFAULT 1,
    CONSTRAINT fk_layout_weekly_weights_layout 
        FOREIGN KEY (layout_id) 
        REFERENCES layout_tasks(id)
);

-- 建立索引以提升查詢效能
CREATE INDEX idx_layout_weekly_weights_layout_week 
    ON layout_weekly_weights(layout_id, week);

-- 建立索引以提升按週查詢效能
CREATE INDEX idx_layout_weekly_weights_week 
    ON layout_weekly_weights(week); 