
-- backend/migrations/layout_task.sql

CREATE TABLE layout_task (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  layout_owner VARCHAR2(50),
  layout_id    VARCHAR2(50),
  stage        VARCHAR2(50),
  owner        VARCHAR2(50),
  percent      NUMBER,
  start_time   DATE,
  end_time     DATE,
  updated_at   TIMESTAMP
);
